### ISSUE TITLE
The price of sts3250 is actually 80.15

### ISSUE THREAD

**Issue by GoingMyWay** [Zeroth-Robotics/OpenLCH#72]
https://www.aliexpress.us/item/3256806337383027.html?gatewayAdapt=glo2usa4itemAdapt

<img width="1288" alt="image" src="https://github.com/user-attachments/assets/17cc8594-7b28-4486-91a9-eb077142b4bc" />

The price of sts3250 is actually 80.15

On Taobao.com the price is RMB 464.

**Comment by lijiajun3029** [comment]
I think this is very expensive.

**Comment by jingxiangmo** [comment]
Yeah the seller has significantly increased the cost of STS3250s... We're getting new custom STS3215s with high RPMs made right now

**Comment by GoingMyWay** [comment]
> Yeah the seller has significantly increased the cost of STS3250s... We're getting new custom STS3215s with high RPMs made right now

Do you mean the price of it was low?

**Comment by jingxiangmo** [comment]
Yup, 3215 was $11 and 3250 was $30. We originally started with 3215, but 3250's performance was better because of the higher RPM so we changed the BoM for 3250 as we're getting custom servos made by new suppliers right now that would be 3215 price but 65 RPM

**Comment by lijiajun3029** [comment]
> Yup, 3215 was $11 and 3250 was $30. We originally started with 3215, but 3250's performance was better because of the higher RPM so we changed the BoM for 3250 as we're getting custom servos made by new suppliers right now that would be 3215 price but 65 RPM

Further consider how much torque and rpm we need in different parts(legs and hands) of the robot？some sts3215 have 19.5kg@7.4v torque and 52rpm@7.4v(but our battery is 12v)
